.github/workflows/gradle-test.yml

- main push 및 PR 시 github action 으로 gradle test 동작
- main push 는 이후 배포 스크립트로 변경
- resolved #3

[추가] main push 및 PR 시 github action 으로 gradle test

---

knowlly-api/src/main/java/kr/co/yapp/api/core/config/SwaggerConfig.java
knowlly-core/src/main/resources/application.yml

- localhost:8080/swagger-ui.html 로 swagger 접근 가능
- close #10

[추가] swagger-ui 설정 추가

---

.gitignore
knowlly-core/src/main/java/kr/co/yapp/core/lecture/entity/Category.java
knowlly-core/src/main/java/kr/co/yapp/core/lecture/entity/Form.java
knowlly-core/src/main/java/kr/co/yapp/core/lecture/entity/Lecture.java
knowlly-core/src/main/java/kr/co/yapp/core/lecture/entity/LectureImage.java
knowlly-core/src/main/java/kr/co/yapp/core/lecture/entity/Schedule.java
knowlly-core/src/main/java/kr/co/yapp/core/lecture/entity/Tag.java
knowlly-core/src/main/java/kr/co/yapp/core/user/entity/BallHistory.java
knowlly-core/src/main/java/kr/co/yapp/core/user/entity/Coach.java
knowlly-core/src/main/java/kr/co/yapp/core/user/entity/Review.java
knowlly-core/src/main/java/kr/co/yapp/core/user/entity/User.java
knowlly-core/src/main/java/kr/co/yapp/core/user/entity/UserImage.java

- https://www.erdcloud.com/d/upxjamqGs5qPfYyXC
- 이후에 엔티티 관계에 대한 테스트 작성 추가 필요
- close #5

[추가] 엔티티 초안 작성

---

build.gradle
knowlly-api/build.gradle
knowlly-api/src/main/java/kr/co/knowledgerally/api/KnowllyApplication.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/core/config/SwaggerConfig.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/core/web/TestController.java
knowlly-core/build.gradle
knowlly-core/src/main/java/kr/co/knowledgerally/core/lecture/entity/Category.java
knowlly-core/src/main/java/kr/co/knowledgerally/core/lecture/entity/Form.java
knowlly-core/src/main/java/kr/co/knowledgerally/core/lecture/entity/Lecture.java
knowlly-core/src/main/java/kr/co/knowledgerally/core/lecture/entity/LectureImage.java
knowlly-core/src/main/java/kr/co/knowledgerally/core/lecture/entity/Schedule.java
knowlly-core/src/main/java/kr/co/knowledgerally/core/lecture/entity/Tag.java
knowlly-core/src/main/java/kr/co/knowledgerally/core/user/entity/BallHistory.java
knowlly-core/src/main/java/kr/co/knowledgerally/core/user/entity/Coach.java
knowlly-core/src/main/java/kr/co/knowledgerally/core/user/entity/Review.java
knowlly-core/src/main/java/kr/co/knowledgerally/core/user/entity/User.java
knowlly-core/src/main/java/kr/co/knowledgerally/core/user/entity/UserImage.java

- 안드로이트 따라 패키지명을 변경
- closes #11

[업무] 패키지명 변경 (#11)

---

.github/workflows/api-test-and-deploy-dev.yml
deployment/deployment-dev.yml
knowlly-api/Dockerfile

- http://dev.hkpark.net/swagger-ui.html 에서 확인 가능
- 개발 DB를 붙이는 작업 추가 필요

[업무] 개발 서버 세팅

---

knowlly-core/src/test/resources/dbunit/entity/ball_history.xml
knowlly-core/src/test/resources/dbunit/entity/category.xml
knowlly-core/src/test/resources/dbunit/entity/coach.xml
knowlly-core/src/test/resources/dbunit/entity/form.xml
knowlly-core/src/test/resources/dbunit/entity/lecture.xml
knowlly-core/src/test/resources/dbunit/entity/lecture_image.xml
knowlly-core/src/test/resources/dbunit/entity/lecture_information.xml
knowlly-core/src/test/resources/dbunit/entity/notification.xml
knowlly-core/src/test/resources/dbunit/entity/review.xml
knowlly-core/src/test/resources/dbunit/entity/tag.xml
knowlly-core/src/test/resources/dbunit/entity/user.xml
knowlly-core/src/test/resources/dbunit/entity/user_image.xml

- 데이터베이스 레벨 단위 테스트를 보다 용이하게 해주는 dbunit의 데이터셋입니다.
- 자세한 사용 방법은 이후 Repository 테스트 작성 시 시연하겠습니다.
- dbunit 데이터셋 추가
- resolved #18 

[추가] dbunit을 위한 데이터셋 파일 추가 (#18)

---

knowlly-core/src/main/java/kr/co/knowledgerally/core/user/entity/User.java
knowlly-core/src/main/resources/config/liquibase/changelog/20220614_add_portfolio_column.xml
knowlly-core/src/test/java/kr/co/knowledgerally/core/user/repository/crud/UserRepositoryCrudTest.java
knowlly-core/src/test/java/kr/co/knowledgerally/core/user/util/TestUserEntityFactory.java
knowlly-core/src/test/resources/dbunit/entity/user.xml
knowlly-core/src/test/resources/dbunit/expected/crud/user_delete_test.xml
knowlly-core/src/test/resources/dbunit/expected/crud/user_insert_test.xml
knowlly-core/src/test/resources/dbunit/expected/crud/user_update_test.xml

- User 테이블에 portfolio 컬럼 추가, 그에 따른 코드 변경
- User 테이블에 identifier 컬럼 추가, 그에 따른 코드 변경
- liquibase, entity, test, dataset 등 user 테이블 관련 코드 수정
- resolved #37
- resolved #47 
PS. PR Approve시에 스키마 변경사항 반영합니다.
edit) #37 반영 전이므로 이 PR에 #47 이슈를 같이 반영합니다.

[수정] User 테이블에 portfolio, identifier 컬럼 추가 (#37)

---

knowlly-api/src/main/java/kr/co/knowledgerally/api/lecture/web/LectureInformationController.java

- LectureInformationController return 타입 수정
- LectureInformationController return 타입 수정 
- resolved #27

[수정] LectureInformationController return 타입 수정 (#27)

---

knowlly-api/src/main/java/kr/co/knowledgerally/api/core/validation/DateTimeStringValidator.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/lecture/component/LectureMapper.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/lecture/dto/LectureDto.java
knowlly-api/src/test/java/kr/co/knowledgerally/api/core/validation/DateTimeStringValidatorTest.java
knowlly-api/src/test/java/kr/co/knowledgerally/api/lecture/component/LectureMapperTest.java
knowlly-api/src/test/java/kr/co/knowledgerally/api/lecture/util/TestLectureDtoFactory.java
knowlly-api/src/test/java/kr/co/knowledgerally/api/lecture/web/LectureControllerTest.java
knowlly-core/src/main/resources/config/liquibase/changelog/20220703_drop_constraint_from_lecture_image.xml
knowlly-core/src/main/resources/config/liquibase/master.xml

- lecture-image 테이블 lecture-information id 컬럼 not null 제약조건 제거  (#108)
- 클래스 일정 등록 시 TimeFormat ISO 8601 형식으로 변경 (#109)
- liquibase 스키마에 변경사항 등록
- 클래스 일정 등록시 날짜 포맷 변경
- 관련 테스트 수정
- resolved #108 
- resolved #109

[수정] #108, #109 수정사항 변경

---

knowlly-api/src/main/java/kr/co/knowledgerally/api/lecture/component/CoachLectureMapper.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/lecture/dto/CoachLectureDto.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/lecture/service/CoachLectureService.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/lecture/service/LectureRegisterService.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/lecture/web/CoachLectureController.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/lecture/web/FormController.java
knowlly-api/src/test/java/kr/co/knowledgerally/api/lecture/component/CoachLectureMapperTest.java
knowlly-api/src/test/java/kr/co/knowledgerally/api/lecture/web/CoachLectureControllerTest.java
knowlly-api/src/test/java/kr/co/knowledgerally/api/lecture/web/FormControllerTest.java
knowlly-core/src/main/java/kr/co/knowledgerally/core/lecture/entity/Lecture.java
knowlly-core/src/main/java/kr/co/knowledgerally/core/lecture/repository/FormRepository.java
knowlly-core/src/main/java/kr/co/knowledgerally/core/lecture/repository/LectureRepository.java
knowlly-core/src/main/java/kr/co/knowledgerally/core/lecture/service/FormService.java
knowlly-core/src/test/java/kr/co/knowledgerally/core/lecture/repository/FormRepositoryTest.java
knowlly-core/src/test/java/kr/co/knowledgerally/core/lecture/repository/LectureRepositoryTest.java
knowlly-core/src/test/java/kr/co/knowledgerally/core/lecture/service/FormServiceTest.java
knowlly-core/src/test/resources/dbunit/entity/form.xml
knowlly-core/src/test/resources/dbunit/entity/lecture.xml
knowlly-core/src/test/resources/dbunit/expected/crud/form_delete_test.xml
knowlly-core/src/test/resources/dbunit/expected/crud/form_update_test.xml
knowlly-core/src/test/resources/dbunit/expected/crud/lecture_delete_test.xml
knowlly-core/src/test/resources/dbunit/expected/crud/lecture_update_test.xml
knowlly-core/src/test/resources/sql/integration.sql

- 운영 클래스 조회 기능 추가
- 운영 클래스 조회 엔드포인트 추가
- 관련 테스트 추가
- resolved #64

[기능] 운영 클래스 조회 기능 추가 (#64)

---

knowlly-api/src/main/java/kr/co/knowledgerally/api/lecture/service/CoachLectureService.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/lecture/web/CategoryController.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/lecture/web/CoachLectureController.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/lecture/web/FormController.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/lecture/web/LectureController.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/lecture/web/LectureInformationController.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/review/web/ReviewCoachController.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/review/web/ReviewUserController.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/user/web/BallHistoryController.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/user/web/UserAuthController.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/user/web/UserController.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/user/web/UserImageController.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/user/web/UserMeController.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/user/web/UserOnboardController.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/user/web/UserSettingController.java

- swagger 문서에 컨트롤러 이름 대신 사용자 친화적인 tag 사용하여 문서 개선
- 컨트롤러: Swagger 문서 어노테이션 tag 추가
- [x] 어플리케이션 구동(혹은 테스트)시 오류는 없는가?
- resolved #85

[문서] Swagger 문서 tag 추가 (#85)

---

knowlly-api/src/main/java/kr/co/knowledgerally/api/lecture/component/LectureInformationMapper.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/lecture/dto/LectureInformationDto.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/lecture/web/LectureInformationController.java
knowlly-api/src/test/java/kr/co/knowledgerally/api/lecture/component/LectureInformationMapperTest.java
knowlly-api/src/test/java/kr/co/knowledgerally/api/lecture/web/LectureInformationControllerTest.java
knowlly-core/src/main/java/kr/co/knowledgerally/core/lecture/entity/LectureInformation.java
knowlly-core/src/main/java/kr/co/knowledgerally/core/lecture/repository/LectureInformationRepository.java
knowlly-core/src/main/java/kr/co/knowledgerally/core/lecture/service/LectureInformationService.java
knowlly-core/src/test/java/kr/co/knowledgerally/core/lecture/repository/LectureInformationRepositoryTest.java
knowlly-core/src/test/java/kr/co/knowledgerally/core/lecture/util/TestLectureInformationEntityFactory.java

- 클래스 상세조회 기능 API
- 클래스 상세조회 기능 API
- resolved #26

[기능] 클래스 상세조회 기능 추가 (#26)

---

build.gradle
knowlly-api/src/main/java/kr/co/knowledgerally/api/KnowllyApiApplication.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/lecture/event/FormRegisterEvent.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/lecture/service/FormRegisterService.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/review/event/ReviewWrittenEvent.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/review/service/ReviewCoachService.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/review/web/ReviewCoachLectureController.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/user/event/BallEventListener.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/user/event/UserSignupEvent.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/user/service/UserSignUpService.java
knowlly-api/src/test/java/kr/co/knowledgerally/api/review/web/ReviewCoachLectureControllerTest.java
knowlly-api/src/test/java/kr/co/knowledgerally/api/user/service/UserSignUpServiceTest.java
knowlly-api/src/test/java/kr/co/knowledgerally/api/user/web/UserAuthControllerTest.java
knowlly-core/src/main/java/kr/co/knowledgerally/core/KnowllyCoreApplication.java
knowlly-core/src/main/java/kr/co/knowledgerally/core/core/annotation/PublishEvent.java
knowlly-core/src/main/java/kr/co/knowledgerally/core/core/vo/EventType.java
knowlly-core/src/main/java/kr/co/knowledgerally/core/user/entity/User.java
knowlly-core/src/main/java/kr/co/knowledgerally/core/user/service/BallService.java
knowlly-core/src/main/java/kr/co/knowledgerally/core/user/vo/BallTransactionVo.java
knowlly-core/src/test/java/kr/co/knowledgerally/core/user/service/BallServiceTest.java
knowlly-core/src/test/resources/dbunit/expected/사용자_볼_증가_테스트.xml

- 이벤드 핸들러 등록, 특정 상황에서 볼 지급 추가
- 이벤트 핸들링 테스트 추가 필요
- 신청서 작성 로직 수정
- 이벤트 핸들러 등록
- 신청서 작성 로직 수정
- 테스트 추가
- resolved #87 

[기능] 이벤트 핸들러 등록, 볼 지급 이벤트 추가 (#87)

---

knowlly-api/src/main/java/kr/co/knowledgerally/api/lecture/component/LectureInformationMapper.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/lecture/dto/CategoryDto.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/lecture/dto/LectureInformationDto.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/lecture/web/CategoryController.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/lecture/web/LectureInformationController.java
knowlly-api/src/test/java/kr/co/knowledgerally/api/lecture/component/CategoryMapperTest.java
knowlly-api/src/test/java/kr/co/knowledgerally/api/lecture/component/CoachLectureMapperTest.java
knowlly-api/src/test/java/kr/co/knowledgerally/api/lecture/component/LectureInformationMapperTest.java
knowlly-api/src/test/java/kr/co/knowledgerally/api/lecture/component/UserLectureMapperTest.java
knowlly-api/src/test/java/kr/co/knowledgerally/api/lecture/util/TestCategoryDtoFactory.java
knowlly-api/src/test/java/kr/co/knowledgerally/api/lecture/util/TestLectureInformationDtoFactory.java
knowlly-api/src/test/java/kr/co/knowledgerally/api/lecture/web/CategoryControllerTest.java
knowlly-api/src/test/java/kr/co/knowledgerally/api/lecture/web/LectureInformationControllerTest.java
knowlly-core/src/main/java/kr/co/knowledgerally/core/lecture/entity/Category.java
knowlly-core/src/main/java/kr/co/knowledgerally/core/lecture/repository/CategoryRepository.java
knowlly-core/src/main/java/kr/co/knowledgerally/core/lecture/repository/LectureInformationRepository.java
knowlly-core/src/main/java/kr/co/knowledgerally/core/lecture/service/CategoryService.java
knowlly-core/src/main/java/kr/co/knowledgerally/core/lecture/service/LectureInformationService.java
knowlly-core/src/test/java/kr/co/knowledgerally/core/lecture/repository/CategoryRepositoryTest.java
knowlly-core/src/test/java/kr/co/knowledgerally/core/lecture/repository/LectureInformationRepositoryTest.java
knowlly-core/src/test/java/kr/co/knowledgerally/core/lecture/repository/crud/CategoryRepositoryCrudTest.java
knowlly-core/src/test/java/kr/co/knowledgerally/core/lecture/service/CategoryServiceTest.java
knowlly-core/src/test/java/kr/co/knowledgerally/core/lecture/service/LectureInformationSearchServiceTest.java
knowlly-core/src/test/java/kr/co/knowledgerally/core/lecture/service/LectureInformationServiceTest.java
knowlly-core/src/test/java/kr/co/knowledgerally/core/lecture/util/TestCategoryEntityFactory.java
knowlly-core/src/test/resources/dbunit/entity/category.xml
knowlly-core/src/test/resources/dbunit/expected/crud/category_delete_test.xml
knowlly-core/src/test/resources/dbunit/expected/crud/category_insert_test.xml
knowlly-core/src/test/resources/dbunit/expected/crud/category_update_test.xml
knowlly-core/src/test/resources/sql/integration.sql

- DB값 수정 및 엔티티 값 enum으로 변경
- 엔드포인트 스키마 수정됨
- DB값 수정 및 엔티티 값 enum으로 변경
- 테스트 수정
- resolved #130

[수정] 카테고리 키 기반 id -> name으로 변경 (#130)

---

.github/workflows/api-test-and-deploy-dev.yml
knowlly-api/src/main/java/kr/co/knowledgerally/api/coach/dto/ReviewDto.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/review/component/ReviewMapper.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/review/dto/ReviewDto.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/review/service/ReviewCoachService.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/review/web/ReviewCoachLectureController.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/review/web/ReviewUserController.java
knowlly-api/src/test/java/kr/co/knowledgerally/api/coach/component/ReviewMapperTest.java
knowlly-api/src/test/java/kr/co/knowledgerally/api/coach/util/TestCoachDtoFactory.java
knowlly-api/src/test/java/kr/co/knowledgerally/api/coach/util/TestReviewDtoFactory.java
knowlly-api/src/test/java/kr/co/knowledgerally/api/review/web/ReviewUserControllerTest.java
knowlly-core/src/main/java/kr/co/knowledgerally/core/coach/entity/Review.java
knowlly-core/src/main/resources/config/liquibase/changelog/20220709_add_class_name_column.xml
knowlly-core/src/main/resources/config/liquibase/master.xml
knowlly-core/src/test/java/kr/co/knowledgerally/core/coach/repository/crud/ReviewRepositoryCrudTest.java
knowlly-core/src/test/java/kr/co/knowledgerally/core/coach/util/TestReviewEntityFactory.java
knowlly-core/src/test/resources/dbunit/entity/review.xml
knowlly-core/src/test/resources/dbunit/expected/crud/review_delete_test.xml
knowlly-core/src/test/resources/dbunit/expected/crud/review_insert_test.xml
knowlly-core/src/test/resources/dbunit/expected/crud/review_update_test.xml
knowlly-core/src/test/resources/sql/integration.sql

- Review 테이블에 class_name 컬럼 추가 및 관련 엔티티, 테스트 코드 수정
- workflow에 liquibase 스키마 업데이트 구문도 추가해봄
- Review className 필드 추가 및 관련 소스코드 수정
- 테스트 수정
- workflow 업데이트
- resolved #136

[수정] Review 테이블에 class_name 컬럼 추가 (#136)

---

knowlly-api/src/main/java/kr/co/knowledgerally/api/core/component/RequestLogFilter.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/core/config/SecurityConfig.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/core/config/WebConfig.java

- RequestLogFilter 순서 변경, param 기록 추가
- Security 설정 변경
- resolved #145

[수정] RequestLogFilter 순서 변경, param 기록 추가 (#145)

---

knowlly-api/src/main/java/kr/co/knowledgerally/api/user/service/UserImageDeleteService.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/user/web/UserImageController.java
knowlly-api/src/test/java/kr/co/knowledgerally/api/user/service/UserImageDeleteServiceTest.java
knowlly-api/src/test/java/kr/co/knowledgerally/api/user/web/UserImageControllerTest.java

- 프로필 이미지 삭제 기능 추가
- 프로필 이미지 삭제 기능 추가
- resolved #159

[기능] 프로필 이미지 삭제 기능 추가(#159)

---

.github/workflows/api-test-and-deploy-dev.yml
deployment/knowlly-batch-dev-deployment.yml
knowlly-batch/Dockerfile
knowlly-batch/src/main/java/kr/co/knowledgerally/batch/lecture/LectureDoneJobConductor.java
knowlly-batch/src/main/java/kr/co/knowledgerally/batch/lecture/LectureDoneService.java

- 시간 만료된 매칭 중인 일정은 비활성화 처리
- 관련 신청서가 존재시 모두 REJECT 처리
- 시간이 만료된 클래스 일정은 active false 처리
- 만약 관련된 Form이 있다면 모두 Reject 처리
- resolved #164 

[수정] 시간이 만료된 클래스 일정은 active false 처리 (#164)

---

.github/workflows/api-test-and-deploy-api-prod.yml
.github/workflows/api-test-and-deploy-batch-prod.yml
.gitignore
deployment/knowlly-api-prod-deployment.yml
deployment/knowlly-batch-prod-deployment.yml
knowlly-api/Dockerfile
knowlly-api/src/main/java/kr/co/knowledgerally/api/core/config/SwaggerConfig.java
knowlly-api/src/test/java/kr/co/knowledgerally/api/core/component/AmazonS3ClientTestProd.java
knowlly-batch/Dockerfile
knowlly-core/src/main/resources/logback-spring.xml

- 지급 받은 NCP에 운영 서버를 구축
- 접속 방법 : https://www.notion.so/sunsetmood/8d33713776a6458ca06720d2ae9c0842
- 개발 환경에 셋팅된 인프라 모두 운영환경으로도 구축 완료
- Api
- Batch
- DB
- Storage
- 추가로, https 구성됨
- CI/CD 구성
- 단, main 브랜치 변동에 따른 자동 배포 제거, 수동 배포로 동작
- 운영 환경 구성에 따른 CI/CD, 로깅 아키텍처, 테스트 구성
- 운영환경은 swagger 제거
- resolved #122

[구성] 운영환경 구성 및 CI/CD 구성 (#122)

---

knowlly-api/src/main/java/kr/co/knowledgerally/api/lecture/service/LectureDeleteService.java
knowlly-api/src/main/java/kr/co/knowledgerally/api/lecture/web/LectureController.java
knowlly-api/src/test/java/kr/co/knowledgerally/api/lecture/service/LectureDeleteServiceTest.java
knowlly-api/src/test/java/kr/co/knowledgerally/api/lecture/web/LectureControllerTest.java
knowlly-core/src/main/java/kr/co/knowledgerally/core/core/message/ErrorMessage.java
knowlly-core/src/main/java/kr/co/knowledgerally/core/lecture/repository/FormRepository.java
knowlly-core/src/main/java/kr/co/knowledgerally/core/lecture/service/FormService.java
knowlly-core/src/test/java/kr/co/knowledgerally/core/lecture/repository/FormRepositoryTest.java
knowlly-core/src/test/java/kr/co/knowledgerally/core/lecture/service/FormServiceTest.java

- 클래스 일정 삭제 기능
- 테스트 코드 작성
- 클래스 일정 삭제 기능
- resolved #163 

[기능] 클래스 일정 삭제 API (#163)
